image: python:2.7

stages:
 - build

before_script:
  - "pip install -U platformio"

job:
  stage: build
  script: 
    - cd uvcrobot_hardware/pwm_motor/
    - platformio run
  variables: {PLATFORMIO_CI_SRC: "/src/main.cpp"}
