image: python:2.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
 - board_build

before_script:
  - "pip install -U platformio"

job:
  stage: board_build
  script: 
    - cd uvcrobot_hardware/pwm_motor/
    - platformio run
  variables: {PLATFORMIO_CI_SRC: "/src/main.cpp"}
